# Generated by Django 5.2.3 on 2025-06-13 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время обнаружения')),
                ('detection_type', models.CharField(choices=[('fire', 'Пожар'), ('smoke', 'Дым'), ('unknown', 'Неизвестно')], default='fire', max_length=10, verbose_name='Тип обнаружения')),
                ('confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Уверенность модели')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fire_detections/%Y/%m/%d/', verbose_name='Изображение с обнаружением')),
                ('video_frame', models.TextField(blank=True, null=True, verbose_name='Кадр видео в base64')),
                ('x1', models.IntegerField(blank=True, null=True, verbose_name='Координата X1')),
                ('y1', models.IntegerField(blank=True, null=True, verbose_name='Координата Y1')),
                ('x2', models.IntegerField(blank=True, null=True, verbose_name='Координата X2')),
                ('y2', models.IntegerField(blank=True, null=True, verbose_name='Координата Y2')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Уведомление отправлено')),
            ],
            options={
                'verbose_name': 'Событие пожара',
                'verbose_name_plural': 'События пожаров',
                'ordering': ['-detection_time'],
                'indexes': [models.Index(fields=['detection_time'], name='api_fireeve_detecti_20cfdc_idx'), models.Index(fields=['detection_type'], name='api_fireeve_detecti_f97633_idx')],
            },
        ),
    ]
