# Generated by Django 5.2.3 on 2025-06-13 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fireevent',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='fireevent',
            name='api_fireeve_detecti_20cfdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='fireevent',
            name='api_fireeve_detecti_f97633_idx',
        ),
        migrations.RemoveField(
            model_name='fireevent',
            name='notification_sent',
        ),
        migrations.RemoveField(
            model_name='fireevent',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='fireevent',
            name='video_frame',
        ),
        migrations.AlterField(
            model_name='fireevent',
            name='confidence',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Уверенность модели'),
        ),
        migrations.AlterField(
            model_name='fireevent',
            name='detection_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время обнаружения'),
        ),
        migrations.AlterField(
            model_name='fireevent',
            name='detection_type',
            field=models.CharField(choices=[('fire', 'Пожар'), ('smoke', 'Дым'), ('unknown', 'Неизвестно')], max_length=10, verbose_name='Тип обнаружения'),
        ),
        migrations.AlterField(
            model_name='fireevent',
            name='image',
            field=models.ImageField(default='fire_detections/default.jpg', upload_to='fire_detections/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='fireevent',
            name='x1',
            field=models.IntegerField(default=0, verbose_name='Координата X1'),
        ),
        migrations.AlterField(
            model_name='fireevent',
            name='x2',
            field=models.IntegerField(default=0, verbose_name='Координата X2'),
        ),
        migrations.AlterField(
            model_name='fireevent',
            name='y1',
            field=models.IntegerField(default=0, verbose_name='Координата Y1'),
        ),
        migrations.AlterField(
            model_name='fireevent',
            name='y2',
            field=models.IntegerField(default=0, verbose_name='Координата Y2'),
        ),
    ]
